### ISSUE TITLE
Explore data variables where instances that have different outcomes

### ISSUE THREAD

**Issue by albertkun** [ucla-lppi/report-generator#14]
#13 only looks at the variable `Temps over 90 degrees`, but we need to look at other indicators.

**Comment by juliaraesilver** [comment]
**San Joaquin County**

**Here are the interpretations that are incorrect and/or need workshopping**:

1. "Latino neighborhoods historically experience more days with high temperatures. For instance, the average number of days with temperatures reaching 90°F between 2018 and 2022 is higher in Latino neighborhoods (114 days) compared to NL White neighborhoods (115 days), representing a significant increase of -1 days."

In this case, the interpretation is inverse of the outputs. 

2. "Latino neighborhoods endure longer heat waves. In recent years, these neighborhoods experienced an average of 71 consecutive days with temperatures at or above 90°F, while NL White neighborhoods experienced 70 consecutive days, a difference of 1 days." 

In this case, the interpretation is technically correct, but I am weary of how the interpretation is presented, considering 71/70 are so close. I encourage us to think through how to present interpretations for similar outputs. We'll talk with the team about 'thresholds' to define these interpretation differences.  Also, it should be "1 day", rather than "1 days." 

3. "Looking forward, Latino neighborhoods are projected to experience a greater number of days with higher temperatures. Between 2035 and 2064, Latino neighborhoods are expected to experience an average of 122 days with temperatures of 90°F or higher, while NL White neighborhoods are expected to experience 121 days, a difference of 1 days."

Same comment as #2.

**Comment by juliaraesilver** [comment]
**Riverside County

Here are the interpretations that are incorrect and/or need workshopping**:

1. "Latino neighborhoods historically experience more days with high temperatures. For instance, the average number of days with temperatures reaching 90°F between 2018 and 2022 is higher in Latino neighborhoods (114 days) compared to NL White neighborhoods (123 days), representing a significant increase of -9 days."

In this case, the interpretation is the inverse of the outputs.

2. "Latino neighborhoods endure longer heat waves. In recent years, these neighborhoods experienced an average of 36 consecutive days.." 

In this case, the interpretation is the inverse of the outputs.

3. Looking forward, Latino neighborhoods are projected to experience a greater number of days with higher temperatures. Between 2035 and 2064, Latino neighborhoods are expected to experience an average of 163 days with temperatures of 90°F or higher, while NL White neighborhoods are expected to experience 190 days, a difference of -27 days."

In this case, the interpretation is the inverse of the outputs.

**Comment by albertkun** [comment]
This is currently being tracked and addressed in #17
